default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: flatiron_connect_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: flatiron_connect_test
  pool: 5

production:
  url: <%= ENV["DATABASE_URL"] %>